# Table Names
TABLE_ROLE = 'roles'
TABLE_USER = 'users'
TABLE_CLUB = 'clubs'
TABLE_NEWS = 'news'
TABLE_NEWS_STATUS = 'nstatus'
TABLE_BOOK = 'books'
TABLE_SESSION = 'sessions'
TABLE_CATEGORY = 'category'
TABLE_EVENT = 'event'
TABLE_EVENT_CATEGORY = 'event_category'
TABLE_REGISTRATION = 'registrations'
TABLE_REGISTRATION_STATUS = 'rstatus'
TABLE_EVENT_REGISTRATION = 'event_registrations'
TABLE_SESSION_REGISTRATION = 'session_registrations'
TABLE_CLUB_REGISTRATION = 'clubs_registrations'
TABLE_CULTURAL_CONTENT = 'infocultura_culturalcontent'
TABLE_EDITORIAL_ACTION = 'editorial_actions'
TABLE_ADMIN_AUDIT_LOG = 'admin_audit_logs'

# Column Names (Common/Specific)
COL_ID = 'id'
COL_ID_ROLE = 'id_role'
COL_ID_CLUBS = 'id_clubs'
COL_ID_NEWS = 'id_news'
COL_ID_NSTATUS = 'id_nstatus'
COL_ID_BOOKS = 'id_books'
COL_ID_SESSIONS = 'id_sessions'
COL_ID_CATEGORY = 'id_category'
COL_ID_EVENT = 'id_event'
COL_ID_REGISTRATIONS = 'id_registrations'
COL_ID_RSTATUS = 'id_rstatus'
COL_ROLE_ID = 'role_id'
COL_USER_ID = 'user_id'
COL_CLUB_ID = 'id_club'  # Some tables use id_club, others id_clubs

# Scheduling Columns
COL_START_DATE = 'start_date'
COL_END_DATE = 'end_date'
COL_CREATED_AT = 'created_at'
COL_UPDATED_AT = 'updated_at'
