import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
function ArrowIcon() {
    return (_jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "ml-1 mt-1 h-4 w-4 shrink-0", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M17 8l4 4m0 0l-4 4m4-4H3" }) }));
}
function NewsHighlightsSection({ title = 'Notícias', viewAllHref, viewAllLabel = 'Ver tudo', viewAllInternal = false, items, className = 'col-span-2 lg:col-span-1 z-10' }) {
    return (_jsxs("section", { className: className, children: [_jsxs("div", { className: "pl-3", children: [_jsx("h2", { className: "font-heading text-3xl font-bold tracking-tight text-black xl:text-4xl 2xl:text-5xl", children: title }), viewAllInternal ? (_jsxs(Link, { to: viewAllHref, className: "ml-1 mt-1 flex items-center text-sm text-gray-500 underline-offset-2 hover:underline", children: [_jsx("span", { children: viewAllLabel }), _jsx(ArrowIcon, {})] })) : (_jsxs("a", { href: viewAllHref, className: "ml-1 mt-1 flex items-center text-sm text-gray-500 underline-offset-2 hover:underline", children: [_jsx("span", { children: viewAllLabel }), _jsx(ArrowIcon, {})] }))] }), _jsx("div", { className: "z-10 mt-2 sm:mt-4", children: items.map((item) => (_jsxs("article", { className: "group relative overflow-hidden border-b-2 border-gray-200 p-3.5", children: [_jsxs("div", { className: "absolute inset-0 z-20 hidden group-hover:block", children: [_jsx("img", { className: "pointer-events-none z-10 aspect-[16/9] w-full object-cover", src: item.image, alt: item.imageAlt, loading: "lazy", decoding: "async" }), _jsx("span", { className: "absolute inset-0 z-10 h-full w-full bg-black bg-opacity-70" })] }), _jsxs("div", { className: "relative z-30", children: [_jsx("time", { className: "text-sm font-semibold uppercase text-orange-400", dateTime: item.publishedAt, children: item.publishedLabel }), _jsx("p", { className: "mt-2 text-md font-bold transition underline-offset-2 group-hover:text-white group-hover:underline lg:text-lg xl:text-xl 2xl:text-2xl", children: item.internal ? _jsx(Link, { to: item.href, children: item.title }) : _jsx("a", { href: item.href, children: item.title }) }), _jsx("p", { className: "mt-1 line-clamp-2 transition group-hover:text-white", children: item.internal ? (_jsx(Link, { to: item.href, children: item.excerpt })) : (_jsx("a", { href: item.href, children: item.excerpt })) }), item.tags && item.tags.length > 0 ? (_jsx("div", { className: "mt-2 flex items-center space-x-3 text-sm text-gray-600 transition group-hover:text-white", children: item.tags.map((tag) => (_jsx("a", { href: tag.href, className: "underline-offset-2 hover:underline", children: tag.label }, tag.href))) })) : null] })] }, item.href))) })] }));
}
export default NewsHighlightsSection;
