from django.urls import path
from .views import (
    AdminBookDetailView,
    AdminBookBulkDeleteView,
    AdminBookListCreateView,
    AdminAuditLogListView,
    AdminDashboardNotificationsView,
    AdminDashboardSummaryView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminClubDetailView,
    AdminClubListCreateView,
    AdminClubMemberAssignView,
    AdminClubMemberRemoveView,
    AdminContentDetailView,
    AdminContentListCreateView,
    AdminEventDetailView,
    AdminEventBulkDeleteView,
    AdminEventBulkStatusUpdateView,
    AdminEventListCreateView,
    AdminImageUploadView,
    AdminNewsDetailView,
    AdminNewsBulkDeleteView,
    AdminNewsBulkStatusUpdateView,
    AdminNewsListCreateView,
    AdminNewsStatusListView,
    AdminRegistrationListView,
    AdminRegistrationBulkStatusUpdateView,
    AdminRegistrationStatusListView,
    AdminRegistrationStatusUpdateView,
    AdminRoleListView,
    AdminSessionDetailView,
    AdminSessionListCreateView,
    AdminUserDeactivateView,
    AdminUserDetailView,
    AdminUserListCreateView,
    LoginView,
    LogoutView,
    PublicBookDetailView,
    PublicBookListView,
    PublicCategoryListView,
    MeView,
    PublicClubDetailView,
    PublicClubRegistrationCreateView,
    PublicClubListView,
    PublicContentListView,
    PublicEventDetailView,
    PublicEventCalendarView,
    PublicEventListView,
    PublicEventRegistrationCreateView,
    PublicNewsDetailView,
    PublicNewsListView,
    PublicNewsStatusListView,
    PublicSessionCalendarView,
    PublicSessionDetailView,
    PublicSessionListView,
    PublicSessionRegistrationCreateView,
    RefreshTokenView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/refresh/', RefreshTokenView.as_view(), name='auth-refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/roles/', AdminRoleListView.as_view(), name='auth-roles'),
    path('auth/users/', AdminUserListCreateView.as_view(), name='auth-users'),
    path('auth/users/<int:pk>/', AdminUserDetailView.as_view(), name='auth-user-detail'),
    path('auth/users/<int:pk>/deactivate/', AdminUserDeactivateView.as_view(), name='auth-user-deactivate'),
    path('clubs/', PublicClubListView.as_view(), name='clubs-public-list'),
    path('clubs/<int:pk>/', PublicClubDetailView.as_view(), name='clubs-public-detail'),
    path(
        'clubs/<int:pk>/registrations/',
        PublicClubRegistrationCreateView.as_view(),
        name='clubs-public-registration-create',
    ),
    path('news/statuses/', PublicNewsStatusListView.as_view(), name='news-statuses-public-list'),
    path('news/', PublicNewsListView.as_view(), name='news-public-list'),
    path('news/<int:pk>/', PublicNewsDetailView.as_view(), name='news-public-detail'),
    path('books/', PublicBookListView.as_view(), name='books-public-list'),
    path('books/<int:pk>/', PublicBookDetailView.as_view(), name='books-public-detail'),
    path('categories/', PublicCategoryListView.as_view(), name='categories-public-list'),
    path('sessions/', PublicSessionListView.as_view(), name='sessions-public-list'),
    path('sessions/<int:pk>/', PublicSessionDetailView.as_view(), name='sessions-public-detail'),
    path(
        'sessions/<int:pk>/registrations/',
        PublicSessionRegistrationCreateView.as_view(),
        name='sessions-public-registration-create',
    ),
    path(
        'sessions/<int:pk>/calendar/',
        PublicSessionCalendarView.as_view(),
        name='sessions-public-calendar',
    ),
    path('events/', PublicEventListView.as_view(), name='events-public-list'),
    path('events/<int:pk>/', PublicEventDetailView.as_view(), name='events-public-detail'),
    path(
        'events/<int:pk>/registrations/',
        PublicEventRegistrationCreateView.as_view(),
        name='events-public-registration-create',
    ),
    path(
        'events/<int:pk>/calendar/',
        PublicEventCalendarView.as_view(),
        name='events-public-calendar',
    ),
    path('content/', PublicContentListView.as_view(), name='content-public-list'),
    path('content/admin/', AdminContentListCreateView.as_view(), name='content-admin-list-create'),
    path('content/admin/<uuid:pk>/', AdminContentDetailView.as_view(), name='content-admin-detail'),
    path('uploads/images/', AdminImageUploadView.as_view(), name='uploads-image-create'),
    path('dashboard/admin/', AdminDashboardSummaryView.as_view(), name='dashboard-admin-summary'),
    path('dashboard/admin/audit/', AdminAuditLogListView.as_view(), name='dashboard-admin-audit'),
    path(
        'dashboard/admin/notifications/',
        AdminDashboardNotificationsView.as_view(),
        name='dashboard-admin-notifications',
    ),
    path('news/admin/statuses/', AdminNewsStatusListView.as_view(), name='news-statuses-admin-list'),
    path('news/admin/bulk-delete/', AdminNewsBulkDeleteView.as_view(), name='news-admin-bulk-delete'),
    path('news/admin/bulk-status/', AdminNewsBulkStatusUpdateView.as_view(), name='news-admin-bulk-status'),
    path('news/admin/', AdminNewsListCreateView.as_view(), name='news-admin-list-create'),
    path('news/admin/<int:pk>/', AdminNewsDetailView.as_view(), name='news-admin-detail'),
    path('books/admin/bulk-delete/', AdminBookBulkDeleteView.as_view(), name='books-admin-bulk-delete'),
    path('books/admin/', AdminBookListCreateView.as_view(), name='books-admin-list-create'),
    path('books/admin/<int:pk>/', AdminBookDetailView.as_view(), name='books-admin-detail'),
    path('sessions/admin/', AdminSessionListCreateView.as_view(), name='sessions-admin-list-create'),
    path('sessions/admin/<int:pk>/', AdminSessionDetailView.as_view(), name='sessions-admin-detail'),
    path('events/admin/', AdminEventListCreateView.as_view(), name='events-admin-list-create'),
    path('events/admin/bulk-delete/', AdminEventBulkDeleteView.as_view(), name='events-admin-bulk-delete'),
    path('events/admin/bulk-status/', AdminEventBulkStatusUpdateView.as_view(), name='events-admin-bulk-status'),
    path('events/admin/<int:pk>/', AdminEventDetailView.as_view(), name='events-admin-detail'),
    path('categories/admin/', AdminCategoryListCreateView.as_view(), name='categories-admin-list-create'),
    path('categories/admin/<int:pk>/', AdminCategoryDetailView.as_view(), name='categories-admin-detail'),
    path(
        'registrations/admin/statuses/',
        AdminRegistrationStatusListView.as_view(),
        name='registrations-admin-statuses-list',
    ),
    path(
        'registrations/admin/',
        AdminRegistrationListView.as_view(),
        name='registrations-admin-list',
    ),
    path(
        'registrations/admin/bulk-status/',
        AdminRegistrationBulkStatusUpdateView.as_view(),
        name='registrations-admin-bulk-status',
    ),
    path(
        'registrations/admin/<int:pk>/status/',
        AdminRegistrationStatusUpdateView.as_view(),
        name='registrations-admin-status-update',
    ),
    path('clubs/admin/', AdminClubListCreateView.as_view(), name='clubs-admin-list-create'),
    path('clubs/admin/<int:pk>/', AdminClubDetailView.as_view(), name='clubs-admin-detail'),
    path('clubs/admin/<int:pk>/members/', AdminClubMemberAssignView.as_view(), name='clubs-admin-member-assign'),
    path('clubs/admin/<int:pk>/members/<int:user_pk>/', AdminClubMemberRemoveView.as_view(), name='clubs-admin-member-remove'),
]
