from django.urls import path
from .views import (
    AdminBookDetailView,
    AdminBookListCreateView,
    AdminClubDetailView,
    AdminClubListCreateView,
    AdminClubMemberAssignView,
    AdminClubMemberRemoveView,
    AdminContentDetailView,
    AdminContentListCreateView,
    AdminEventDetailView,
    AdminEventListCreateView,
    AdminImageUploadView,
    AdminNewsDetailView,
    AdminNewsListCreateView,
    AdminNewsStatusListView,
    AdminRegistrationListView,
    AdminRegistrationStatusListView,
    AdminRegistrationStatusUpdateView,
    AdminRoleListView,
    AdminSessionDetailView,
    AdminSessionListCreateView,
    AdminUserDeactivateView,
    AdminUserDetailView,
    AdminUserListCreateView,
    LoginView,
    PublicBookListView,
    MeView,
    PublicClubDetailView,
    PublicClubRegistrationCreateView,
    PublicClubListView,
    PublicContentListView,
    PublicEventListView,
    PublicNewsDetailView,
    PublicNewsListView,
    PublicNewsStatusListView,
    PublicSessionListView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('auth/roles/', AdminRoleListView.as_view(), name='auth-roles'),
    path('auth/users/', AdminUserListCreateView.as_view(), name='auth-users'),
    path('auth/users/<int:pk>/', AdminUserDetailView.as_view(), name='auth-user-detail'),
    path('auth/users/<int:pk>/deactivate/', AdminUserDeactivateView.as_view(), name='auth-user-deactivate'),
    path('clubs/', PublicClubListView.as_view(), name='clubs-public-list'),
    path('clubs/<int:pk>/', PublicClubDetailView.as_view(), name='clubs-public-detail'),
    path(
        'clubs/<int:pk>/registrations/',
        PublicClubRegistrationCreateView.as_view(),
        name='clubs-public-registration-create',
    ),
    path('news/statuses/', PublicNewsStatusListView.as_view(), name='news-statuses-public-list'),
    path('news/', PublicNewsListView.as_view(), name='news-public-list'),
    path('news/<int:pk>/', PublicNewsDetailView.as_view(), name='news-public-detail'),
    path('books/', PublicBookListView.as_view(), name='books-public-list'),
    path('sessions/', PublicSessionListView.as_view(), name='sessions-public-list'),
    path('events/', PublicEventListView.as_view(), name='events-public-list'),
    path('content/', PublicContentListView.as_view(), name='content-public-list'),
    path('content/admin/', AdminContentListCreateView.as_view(), name='content-admin-list-create'),
    path('content/admin/<uuid:pk>/', AdminContentDetailView.as_view(), name='content-admin-detail'),
    path('uploads/images/', AdminImageUploadView.as_view(), name='uploads-image-create'),
    path('news/admin/statuses/', AdminNewsStatusListView.as_view(), name='news-statuses-admin-list'),
    path('news/admin/', AdminNewsListCreateView.as_view(), name='news-admin-list-create'),
    path('news/admin/<int:pk>/', AdminNewsDetailView.as_view(), name='news-admin-detail'),
    path('books/admin/', AdminBookListCreateView.as_view(), name='books-admin-list-create'),
    path('books/admin/<int:pk>/', AdminBookDetailView.as_view(), name='books-admin-detail'),
    path('sessions/admin/', AdminSessionListCreateView.as_view(), name='sessions-admin-list-create'),
    path('sessions/admin/<int:pk>/', AdminSessionDetailView.as_view(), name='sessions-admin-detail'),
    path('events/admin/', AdminEventListCreateView.as_view(), name='events-admin-list-create'),
    path('events/admin/<int:pk>/', AdminEventDetailView.as_view(), name='events-admin-detail'),
    path(
        'registrations/admin/statuses/',
        AdminRegistrationStatusListView.as_view(),
        name='registrations-admin-statuses-list',
    ),
    path(
        'registrations/admin/',
        AdminRegistrationListView.as_view(),
        name='registrations-admin-list',
    ),
    path(
        'registrations/admin/<int:pk>/status/',
        AdminRegistrationStatusUpdateView.as_view(),
        name='registrations-admin-status-update',
    ),
    path('clubs/admin/', AdminClubListCreateView.as_view(), name='clubs-admin-list-create'),
    path('clubs/admin/<int:pk>/', AdminClubDetailView.as_view(), name='clubs-admin-detail'),
    path('clubs/admin/<int:pk>/members/', AdminClubMemberAssignView.as_view(), name='clubs-admin-member-assign'),
    path('clubs/admin/<int:pk>/members/<int:user_pk>/', AdminClubMemberRemoveView.as_view(), name='clubs-admin-member-remove'),
]
