import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Inbox } from 'lucide-react';
import AdminPageHero from './components/AdminPageHero.js';
import { formatAdminDateTime } from './utils';
import { adminActions, adminBtnDanger, adminBtnEdit, adminBtnPrimary, adminBtnSecondary, adminError, adminField, adminFieldSpaced, adminFormGridSpaced, adminInfo, adminInput, adminLabel, adminListTools, adminPanelCard, adminStatCard, adminStatLabel, adminStatValue, adminStatsGrid, adminUserEmail, adminUserItem, adminUserList, adminUserMeta, adminUserName, adminUserStatus, adminUserStatusActive, adminUserStatusInactive, blockText, blockTitle, } from '../../styles/ui';
function getRegistrationStatusBadge(status) {
    const normalized = status.trim().toLowerCase();
    if (normalized === 'approved') {
        return `${adminUserStatus} ${adminUserStatusActive}`;
    }
    if (normalized === 'rejected' || normalized === 'cancelled') {
        return `${adminUserStatus} ${adminUserStatusInactive}`;
    }
    return `${adminUserStatus} bg-amber-100 text-amber-700`;
}
function RegistrationsPage({ registrationOverviewStats, isExportingRegistrations, handleExportRegistrationsCsv, registrationTotal, pendingRegistrations, approvedRegistrations, rejectedRegistrations, canManageUsers, clubs, registrationClubFilter, setRegistrationClubFilter, registrationStatusFilter, setRegistrationStatusFilter, isLoadingRegistrationStatuses, registrationStatuses, registrationDateFrom, setRegistrationDateFrom, registrationDateTo, setRegistrationDateTo, handleRegistrationSearchSubmit, registrationSearchInput, setRegistrationSearchInput, setRegistrationSearch, setRegistrationPage, registrationError, registrationOrder, setRegistrationOrder, selectedRegistrationIds, setSelectedRegistrationIds, bulkRegistrationStatus, setBulkRegistrationStatus, isApplyingBulkRegistrations, handleApplyBulkRegistrationStatus, isLoadingRegistrations, registrationPage, registrationTotalPages, registrations, updatingRegistrationId, handleUpdateRegistrationStatus, toggleSelectedId, }) {
    return (_jsxs("div", { className: "space-y-6", children: [_jsx(AdminPageHero, { icon: Inbox, title: "Inscricoes", description: "Consulta, triagem e validacao dos pedidos submetidos pelos clubes.", tone: "rose", stats: registrationOverviewStats, actions: _jsx("button", { type: "button", className: adminBtnSecondary, disabled: isExportingRegistrations, onClick: () => void handleExportRegistrationsCsv(), children: isExportingRegistrations ? 'A exportar...' : 'Exportar CSV' }) }), _jsxs("section", { className: adminPanelCard, children: [_jsx("h2", { className: blockTitle, children: "Inscricoes" }), _jsx("p", { className: blockText, children: "Consulta os pedidos submetidos pelos clubes e atualiza o respetivo estado." }), _jsxs("div", { className: adminStatsGrid, children: [_jsxs("div", { className: adminStatCard, children: [_jsx("p", { className: adminStatValue, children: registrationTotal }), _jsx("p", { className: adminStatLabel, children: "Total filtrado" })] }), _jsxs("div", { className: adminStatCard, children: [_jsx("p", { className: adminStatValue, children: pendingRegistrations }), _jsx("p", { className: adminStatLabel, children: "Pendentes na pagina" })] }), _jsxs("div", { className: adminStatCard, children: [_jsx("p", { className: adminStatValue, children: approvedRegistrations }), _jsx("p", { className: adminStatLabel, children: "Aprovadas na pagina" })] }), _jsxs("div", { className: adminStatCard, children: [_jsx("p", { className: adminStatValue, children: rejectedRegistrations }), _jsx("p", { className: adminStatLabel, children: "Rejeitadas na pagina" })] })] }), _jsxs("div", { className: adminFormGridSpaced, children: [canManageUsers ? (_jsxs("div", { className: adminField, children: [_jsx("label", { className: adminLabel, htmlFor: "registration-club-filter", children: "Clube" }), _jsxs("select", { id: "registration-club-filter", className: adminInput, value: registrationClubFilter, onChange: (event) => {
                                            setRegistrationClubFilter(event.target.value);
                                            setRegistrationPage(1);
                                        }, children: [_jsx("option", { value: "all", children: "Todos os clubes" }), clubs.map((club) => (_jsx("option", { value: club.id, children: club.name }, club.id)))] })] })) : null, _jsxs("div", { className: adminField, children: [_jsx("label", { className: adminLabel, htmlFor: "registration-status-filter", children: "Estado" }), _jsxs("select", { id: "registration-status-filter", className: adminInput, value: registrationStatusFilter, onChange: (event) => {
                                            setRegistrationStatusFilter(event.target.value);
                                            setRegistrationPage(1);
                                        }, children: [_jsx("option", { value: "all", children: "Todos" }), isLoadingRegistrationStatuses ? _jsx("option", { value: "", children: "A carregar estados..." }) : null, registrationStatuses.map((status) => (_jsx("option", { value: status.name, children: status.name }, status.id)))] })] }), _jsxs("div", { className: adminField, children: [_jsx("label", { className: adminLabel, htmlFor: "registration-date-from", children: "Submetidas desde" }), _jsx("input", { id: "registration-date-from", type: "date", className: adminInput, value: registrationDateFrom, onChange: (event) => setRegistrationDateFrom(event.target.value) })] }), _jsxs("div", { className: adminField, children: [_jsx("label", { className: adminLabel, htmlFor: "registration-date-to", children: "Submetidas ate" }), _jsx("input", { id: "registration-date-to", type: "date", className: adminInput, value: registrationDateTo, onChange: (event) => setRegistrationDateTo(event.target.value) })] })] }), _jsxs("form", { onSubmit: handleRegistrationSearchSubmit, className: adminFieldSpaced, children: [_jsx("label", { className: adminLabel, htmlFor: "registration-search", children: "Pesquisar por nome ou email" }), _jsxs("div", { className: adminActions, children: [_jsx("input", { id: "registration-search", className: adminInput, value: registrationSearchInput, onChange: (event) => setRegistrationSearchInput(event.target.value), placeholder: "Ex.: maria ou maria@email.pt" }), _jsx("button", { type: "submit", className: adminBtnPrimary, children: "Pesquisar" }), _jsx("button", { type: "button", className: adminBtnSecondary, onClick: () => {
                                            setRegistrationSearchInput('');
                                            setRegistrationSearch('');
                                            setRegistrationPage(1);
                                        }, children: "Limpar" }), _jsx("button", { type: "button", className: adminBtnSecondary, disabled: isExportingRegistrations, onClick: () => void handleExportRegistrationsCsv(), children: isExportingRegistrations ? 'A exportar...' : 'Exportar CSV' })] })] }), registrationError ? _jsx("p", { className: adminError, children: registrationError }) : null, _jsxs("div", { className: adminActions, children: [_jsxs("select", { className: adminInput, value: registrationOrder, onChange: (event) => setRegistrationOrder(event.target.value), children: [_jsx("option", { value: "newest", children: "Mais recentes" }), _jsx("option", { value: "oldest", children: "Mais antigas" }), _jsx("option", { value: "name_asc", children: "Nome A-Z" }), _jsx("option", { value: "name_desc", children: "Nome Z-A" }), _jsx("option", { value: "email_asc", children: "Email A-Z" }), _jsx("option", { value: "email_desc", children: "Email Z-A" }), _jsx("option", { value: "club_asc", children: "Clube A-Z" }), _jsx("option", { value: "club_desc", children: "Clube Z-A" }), _jsx("option", { value: "status_asc", children: "Estado A-Z" }), _jsx("option", { value: "status_desc", children: "Estado Z-A" })] }), _jsx("button", { type: "button", className: adminBtnSecondary, onClick: () => setSelectedRegistrationIds(selectedRegistrationIds.length === registrations.length
                                    ? []
                                    : registrations.map((item) => item.id)), disabled: registrations.length === 0, children: selectedRegistrationIds.length === registrations.length && registrations.length > 0
                                    ? 'Limpar selecao'
                                    : 'Selecionar pagina' }), _jsx("select", { className: adminInput, value: bulkRegistrationStatus, onChange: (event) => setBulkRegistrationStatus(event.target.value), children: registrationStatuses.map((status) => (_jsx("option", { value: status.name, children: status.name }, status.id))) }), _jsx("button", { type: "button", className: adminBtnPrimary, disabled: selectedRegistrationIds.length === 0 || isApplyingBulkRegistrations, onClick: () => void handleApplyBulkRegistrationStatus(), children: isApplyingBulkRegistrations ? 'A aplicar...' : 'Aplicar em lote' })] }), !isLoadingRegistrations ? (_jsxs("div", { className: adminActions, children: [_jsxs("p", { className: blockText, children: ["Pagina ", registrationPage, registrationTotalPages > 0 ? ` de ${registrationTotalPages}` : '', " \u00B7", ' ', registrationTotal, " resultado", registrationTotal === 1 ? '' : 's'] }), _jsxs("div", { className: adminActions, children: [_jsx("button", { type: "button", className: adminBtnSecondary, disabled: registrationPage <= 1, onClick: () => setRegistrationPage((prev) => Math.max(1, prev - 1)), children: "Anterior" }), _jsx("button", { type: "button", className: adminBtnSecondary, disabled: registrationTotalPages === 0 || registrationPage >= registrationTotalPages, onClick: () => setRegistrationPage((prev) => registrationTotalPages === 0
                                            ? prev
                                            : Math.min(registrationTotalPages, prev + 1)), children: "Seguinte" })] })] })) : null, _jsxs("div", { className: adminUserList, children: [isLoadingRegistrations ? _jsx("p", { className: adminInfo, children: "A carregar inscricoes..." }) : null, !isLoadingRegistrations && registrations.length === 0 ? (_jsx("p", { className: adminInfo, children: "Nao existem inscricoes para os filtros atuais." })) : null, registrations.map((registration) => (_jsxs("article", { className: adminUserItem, children: [_jsxs("div", { children: [_jsxs("label", { className: "mb-2 flex items-center gap-2 text-sm text-slate-600", children: [_jsx("input", { type: "checkbox", checked: selectedRegistrationIds.includes(registration.id), onChange: () => toggleSelectedId(setSelectedRegistrationIds, registration.id) }), "Selecionar"] }), _jsx("h3", { className: adminUserName, children: registration.name }), _jsx("p", { className: adminUserEmail, children: registration.email }), _jsxs("p", { className: adminUserMeta, children: [registration.club_name, " \u00B7 ", formatAdminDateTime(registration.created_at)] }), registration.phone ? (_jsxs("p", { className: adminUserMeta, children: ["Telefone: ", registration.phone] })) : null, _jsx("p", { className: adminUserMeta, children: registration.message || 'Sem mensagem adicional.' })] }), _jsxs("div", { className: adminListTools, children: [_jsx("span", { className: getRegistrationStatusBadge(registration.status), children: registration.status }), _jsx("button", { type: "button", className: adminBtnEdit, disabled: updatingRegistrationId === registration.id ||
                                                    registration.status === 'approved', onClick: () => handleUpdateRegistrationStatus(registration.id, 'approved'), children: updatingRegistrationId === registration.id ? 'A atualizar...' : 'Aprovar' }), _jsx("button", { type: "button", className: adminBtnDanger, disabled: updatingRegistrationId === registration.id ||
                                                    registration.status === 'rejected', onClick: () => handleUpdateRegistrationStatus(registration.id, 'rejected'), children: updatingRegistrationId === registration.id ? 'A atualizar...' : 'Rejeitar' }), _jsx("button", { type: "button", className: adminBtnSecondary, disabled: updatingRegistrationId === registration.id ||
                                                    registration.status === 'pending', onClick: () => handleUpdateRegistrationStatus(registration.id, 'pending'), children: updatingRegistrationId === registration.id ? 'A atualizar...' : 'Pendente' })] })] }, registration.id)))] })] })] }));
}
export default RegistrationsPage;
