import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { useLocale, getLocaleText } from '../../i18n/locale.js';
function PublicMediaListItem({ title, href, imageUrl, imageAlt, dateTime, formattedDate, description, tags }) {
    const { locale } = useLocale();
    return (_jsxs("article", { children: [tags ? _jsx("div", { className: "flex flex-wrap gap-2", children: tags }) : null, _jsxs("div", { className: "mt-2 flex flex-col items-start gap-5 lg:flex-row lg:gap-14", children: [_jsxs("div", { className: "order-2 w-full grow lg:order-1 lg:w-auto", children: [_jsx("h2", { className: "text-2xl font-bold tracking-tight sm:text-3xl lg:text-4xl", children: _jsx(Link, { to: href, className: "underline-offset-3 hover:underline", children: title }) }), _jsx("time", { className: "mt-3 inline-block text-sm font-medium capitalize text-gray-500", dateTime: dateTime, children: formattedDate }), _jsx("p", { className: "mt-3 max-w-3xl text-sm leading-7 text-slate-700 sm:text-base", children: description }), _jsx("div", { className: "mt-3", children: _jsxs(Link, { to: href, className: "flex items-center text-sm font-medium text-orange-400 underline-offset-2 hover:underline", children: [_jsx("span", { children: getLocaleText(locale, 'Ler Mais', 'Read More') }), _jsx(ArrowRight, { "aria-hidden": "true", className: "ml-2 mt-0.5 h-5 w-5", strokeWidth: 2 })] }) })] }), _jsx("div", { className: "relative order-1 w-full shrink-0 overflow-hidden rounded shadow-xl lg:order-2 lg:w-auto", children: _jsx(Link, { to: href, children: _jsx("img", { className: "aspect-[16/9] w-full object-cover transition-transform duration-300 ease-in-out hover:scale-105 lg:aspect-[4/2] lg:max-w-lg lg:mx-auto", src: imageUrl, alt: imageAlt }) }) })] })] }));
}
export default PublicMediaListItem;
